layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: kunal-kapur-0754831b1
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: COSMOS
    web_url: https://jacobsschool.ucsd.edu/cosmos
    image_url: https://jacobsschool.ucsd.edu/sites/default/files/groups/cosmos/img/homepage/banner_2.jpg

  - name: Summer Research 
    web_url: https://www.summer.ucsb.edu/pre-college/summer-research-academies-sra
    image_url: https://jacobsschool.ucsd.edu/cosmos

  - name: Robotics
    web_url: https://www.summer.ucsb.edu/pre-college/summer-research-academies-sra
    image_url: https://jacobsschool.ucsd.edu/cosmos

  - name: Pictures
    web_url: https://github.com/topics/sass
    image_url: img/IMG_8820.jpg

theme: jekyll-theme-dinky
